### ISSUE TITLE
Google Maps TS Types

### ISSUE THREAD

**Issue by medfx** [chancezeus/oms#3]
Hi,
The official google maps typescript types has changed. The current types definitions are in @types/google.maps (https://www.npmjs.com/package/@types/google.maps).
Could you please update the types? The google maps js tools have already updated, but I cant update to them because of types conflicts.
Thanks!

**Comment by medfx** [comment]
Thanks for the adaptation. Could you please also register a new version in NPM?
It still shows 1.0.3 as the current/newest version.
Thanks!

**Comment by chancezeus** [comment]
I will as soon as I have a feedback on the open issue since I fixed the typings as part of fixing the bug of #4 but since I don't have a setup for using the package @ the moment I need somebody to test the build (it's a "npm pack" inside the zip attached to my message there which you should be able to install using npm). If there are no problems then I can publish it (there is however a breaking change in the API of the plugin and that is that 2 methods now return a promise instead of a plain array of markers)
